######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 12:23:19 2014
######################################################################

TEMPLATE = lib
CONFIG -= qt
CONFIG += staticlib
TARGET = ../bin/logging
INCLUDEPATH += .. ../..
OBJECTS_DIR = .objs
QMAKE_CXXFLAGS += -std=c++0x -g -fno-omit-frame-pointer
QMAKE_CLEAN += $(TARGET) $(QMAKE_TARGET) ../bin/liblogging.a

# Input
HEADERS += *.h

SOURCES += *.cpp
