/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "report_item_constants.h"



const report_itemConstants g_report_item_constants;

report_itemConstants::report_itemConstants() {
}



