/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef report_item_CONSTANTS_H
#define report_item_CONSTANTS_H

#include "report_item_types.h"



class report_itemConstants {
 public:
  report_itemConstants();

};

extern const report_itemConstants g_report_item_constants;



#endif
